global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Regras de alertas 
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Configuração de scraping
scrape_configs:
  # Job para o Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job para a API .NET
  - job_name: 'api-dotnet'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Job para Node Exporter (métricas do sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Job para Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

# Configuração de alertas 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093